### PR TITLE
link update

### PR DESCRIPTION
**Pull request by christophergandrud**
Noticed that the previous link was-404. Not sure, but I think the corrected one is the most relevant.

### CODE REVIEW

**Comment by zmjones** [comment]
ah yep, need to change the title too, though it is just a working title. thanks

**Comment by christophergandrud** [comment]
(almost didn't make the pull request because its really minor). 

Looking forward to this work. It's really interesting.

**Comment by zmjones** [comment]
not too minor imo. the package is sort of a minor contribution imo but hopefully will be practically helpful. it will be rewritten pretty substantially when @flinder and I get the time.

**Comment by christophergandrud** [comment]
> "the package is sort of a minor contribution" 

Maybe, but methods papers that don't implement their methods can sometimes feel half-written. 

Nagging thoughts I sometimes have: if the author didn't implement it in an R package, for example, does that mean that they don't plan to actually use the method in their research? And if so, why should anyone else invest time to learn how to use it?

**Comment by zmjones** [comment]
i certainly agree with that.

On Tue, Jan 20, 2015 at 12:03 PM, Christopher Gandrud <
notifications@github.com> wrote:

> "the package is sort of a minor contribution"
>
> Maybe, but methods papers that don't implement their methods can sometimes
> feel half-written.
>
> Nagging thoughts I sometimes have: if the author didn't implement it in an
> R package, for example, does that mean that they don't plan to actually use
> the method in their research? And if so, why should anyone else invest time
> to learn how to use it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/zmjones/edarf/pull/11#issuecomment-70690815>.
>



-- 
Zachary M. Jones
zmjones.com

**Pull request merged**
