### PR TITLE
Fixed Unnecessary duplication when using factors

### PR DESCRIPTION
**Pull request by reuning**
This checks for factor variables, and adjust the cutoffs so it doesn't create duplicate predictions, especially useful for when checking interactions. Example: In the previous version if you were going to generated PD for a continuous variable from Z=1:5 and a factor X=(Yes, No) and if the cutoff was 5, it would create 5^2 variables. (as it didn't realize it would do 5 levels for X even though there were only 2 proper levels). This version will automatically only create 10 predictions in such an instance: Z=1:5 when X=Yes, and Z=1:5 when X=No. 

It isn't exactly pretty. But it does work with the cases I tried.

### CODE REVIEW

**Comment by zmjones** [comment]
Good catch. I think I solved this in 4ce5429561289021b192835be79fcbab95d9a1c4 by just changing one line in `.ivar_points`. Let me know if that solves the problem. Then I'll close this.

**Comment by reuning** [comment]
I think it still has a problem. Specifically line 197   rng <-
as.data.frame(rng)

With different length lists the data.frame does not appreciate there being
different length lists in rng. I am not sure what the simplest way is to
fix this.

I fixed it an uploaded it to my fork. I havne't run the test though yet and
see that it failed last time so it might have issues.

Also the plot_pd has issues now.

Two steps forward 5 backwards?

**Comment by zmjones** [comment]
Ah OK. I will look at this some more tonight.

**Comment by zmjones** [comment]
I made another simple change. Just drop duplicate "observations" in the prediction grid. It worked with the simple example I have (look below). As you noted the plot is broken when `interaction = FALSE`. I think this should work though. It doesn't seem unreasonable to me to request bivariate partial dependence for a set of features of mixed type. I think unfortunately this will require me to just coerce the factor to an integer and (also unfortunately) ggplot2 won't allow me to disable lines being drawn for unordered factors, but I could at least generate a warning for this case.

**Comment by zmjones** [comment]
ping!

**Comment by reuning** [comment]
I am waiting until after I have my paper drafted to get back to this. I
need to finish it up and would rather not mess with things until after that
:P

**Comment by zmjones** [comment]
pishaw

**Comment by zmjones** [comment]
this is fixed

**Pull request closed without merging**
